[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "colight-wire-protocol"
version = "0.1.0"
description = "Binary wire protocol for efficient array transfer."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.22,<2.0.0",
]

[[project.authors]]
name = "Matthew Huebert"
email = "me@matt.is"

[project.license]
text = "Apache-2.0"

[tool.hatch.build]
ignore-vcs = true

[tool.hatch.build.targets.wheel]
packages = ["src/colight_wire_protocol"]
